CREATE TABLE leyendOfEpics (
  id INT(30) PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) DEFAULT NULL,
  captain VARCHAR(100) DEFAULT NULL,
  team TEXT DEFAULT NULL,
  members TEXT DEFAULT NULL,
  date VARCHAR(200) DEFAULT NULL
);